### ISSUE TITLE
BUG: FileNotFoundError

### ISSUE THREAD

**Issue by Junyi-99** [antoniosarosi/pycritty#14]
Cannot touch a file before create the folder, so it should create a folder first then touch the file.

<img width="1273" alt="Screenshot 2023-08-15 at 6 33 16 PM" src="https://github.com/antoniosarosi/pycritty/assets/14367694/fbb95584-d386-44a3-acf7-d0f49469a9e4">

**Comment by antoniosarosi** [comment]
Interesting, does this happen on Mac only?
The `.config/pycritty` directory should be created when installing the package with `pip install` (see [here](https://github.com/antoniosarosi/pycritty/blob/master/setup.py#L26)) but I guess the code should check that again at runtime. I'll take a look when I have time, meanwhile if you want to submit a PR here are some ideas:

- In the [`main`](https://github.com/antoniosarosi/pycritty/blob/master/pycritty/main.py#L15) function, check if `resources.pycritty_dir` exists before doing anything, if it doesn't terminate the program with a `log.error` message.
- Same as before but instead of terminating the program, create the directory, log a warning and continue.
- Third option, change the [`get_or_create_method`](https://github.com/antoniosarosi/pycritty/blob/bf785c5aa464358f5b692832562fd983bd407b0f/pycritty/resources/resource.py#L18) to create all the parent directories if they don't exist. It could be changed in the `Resource` class or maybe overriden in the `ConfigFile`, it should create the parent directory then call the parent class method to create the file.

**Comment by Junyi-99** [comment]
The bug was found on my Intel Mac, but I also reproduced this problem on a m1 Mac, see this picture:

<img width="612" alt="image" src="https://github.com/antoniosarosi/pycritty/assets/14367694/8a7fc839-97f3-478c-a44d-35fd2f10d4c6">

The folder was not created.

**Comment by Junyi-99** [comment]
But when I try to install the package manually it creates a folder

<img width="1116" alt="image" src="https://github.com/antoniosarosi/pycritty/assets/14367694/ad46d9fc-16fa-43d0-a5ee-51c3dfb9f9a1">
